flurga:
  # Username and password for Flurga login
  username: admin
  password: default123
  timezone: Europe/Rome
  lang: en
  
frigate: # Frigate Instances
  0: # Progressive number
    ip: 192.168.144.16:5000 # Frigate IP
    cameras: # Cameras list
      - CAM1
      - CAM2

  1:
    ip: 192.168.144.20:5000
    cameras:
      - CAM3
      - CAM4