flurga:
  username: admin
  password: default123
  timezone: Europe/Rome
  lang: en # Supported: en, es, fr, it
  
frigate:
  0: # Progressive number
    ip: 192.168.144.16:5000 # Frigate IP
    cameras:
      - CAM1
      - CAM2

  1:
    ip: 192.168.144.20:5000
    cameras:
      - CAM3
      - CAM4