version: '3.3'
services:
    flurga:
        container_name: Flurga
        restart: unless-stopped
        ports:
            - '8080:8080'
        volumes:
            - '~/flurga/config.yml:/flurga/config.yml'
        image: 'bthuderous/flurga:latest'