version: '3.3'

volumes:
  flurga:

services:
  flurga:
    container_name: Flurga
    restart: unless-stopped
    volumes:
      - flurga:/home/Flurga
    ports:
      - '1923:1923'
    image: 'ghcr.io/vcardoneit/flurga'