# Generated by Django 4.1.7 on 2023-04-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frigateIP', models.CharField(max_length=255)),
                ('cams', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.IntegerField(default=300)),
            ],
        ),
    ]
